"""add personal api key columns to users

Revision ID: 5d9d1b08fe59
Revises: f4e46aec66d7
Create Date: 2026-04-11 00:59:03.035001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9d1b08fe59'
down_revision: Union[str, None] = 'f4e46aec66d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('api_key_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('api_key_prefix', sa.String(length=12), nullable=True))
    op.add_column('users', sa.Column('api_key_created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    op.drop_column('users', 'api_key_created_at')
    op.drop_column('users', 'api_key_prefix')
    op.drop_column('users', 'api_key_encrypted')
    op.drop_column('users', 'api_key_hash')
    # ### end Alembic commands ###
