"""add_missing_tables_budget_periods_allocations

Revision ID: ce6317ef5e2d
Revises: 015_schema_v2
Create Date: 2026-04-08 12:34:04.900477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce6317ef5e2d'
down_revision: Union[str, None] = '015_schema_v2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_start_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_periods_user_id'), 'budget_periods', ['user_id'], unique=True)
    op.create_table('news_articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_icon', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('related_asset', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_news_category_created', 'news_articles', ['category', 'created_at'], unique=False)
    op.create_index('ix_news_external_id', 'news_articles', ['external_id'], unique=False)
    op.create_table('news_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('avg_sentiment_score', sa.Float(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('article_ids', sa.Text(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clusters_category', 'news_clusters', ['category'], unique=False)
    op.create_index('ix_clusters_created', 'news_clusters', ['created_at'], unique=False)
    op.create_table('asset_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_krw', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_snapshot_user_date')
    )
    op.create_table('budget_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'period_start', name='uq_allocation_user_cat_period')
    )
    op.create_index(op.f('ix_budget_allocations_user_id'), 'budget_allocations', ['user_id'], unique=False)
    op.alter_column('accounts', 'account_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('cash', 'deposit', 'savings', 'parking', 'investment', name='accounttype', native_enum=False),
               existing_nullable=False)
    op.alter_column('accounts', 'interest_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('simple', 'compound', name='interesttype', native_enum=False),
               existing_nullable=True)
    op.alter_column('ai_insights', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('api_keys', 'service',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('tavily', 'serpapi', 'openai', 'anthropic', 'google', 'mistral', 'custom_llm', name='api_service_type_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('categories', 'direction',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('income', 'expense', name='categorydirection', native_enum=False),
               existing_nullable=False)
    op.alter_column('entries', 'type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('income', 'expense', 'transfer_in', 'transfer_out', 'buy', 'sell', 'dividend', 'interest', 'fee', 'adjustment', name='entrytype', native_enum=False),
               existing_nullable=False)
    op.alter_column('entry_groups', 'group_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('transfer', 'trade', 'adjustment', name='grouptype', native_enum=False),
               existing_nullable=False)
    op.alter_column('goal_assets', 'target_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=18, scale=0),
               existing_nullable=False)
    op.alter_column('portfolio_targets', 'target_ratio',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('rebalancing_alerts', 'threshold',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('recurring_schedules', 'type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('income', 'expense', 'transfer', name='scheduletype', native_enum=False),
               existing_nullable=False)
    op.alter_column('securities', 'asset_class',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('equity_kr', 'equity_us', 'commodity', 'currency_pair', name='assetclass', native_enum=False),
               existing_nullable=False)
    op.alter_column('securities', 'data_source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('yahoo', 'manual', name='datasource', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'yahoo'"))
    op.alter_column('users', 'default_currency',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'KRW'"))
    op.drop_column('users', 'salary_amount')
    op.drop_column('users', 'salary_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salary_day', mysql.INTEGER(), server_default=sa.text("'25'"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('salary_amount', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('users', 'default_currency',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'KRW'"))
    op.alter_column('securities', 'data_source',
               existing_type=sa.Enum('yahoo', 'manual', name='datasource', native_enum=False),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'yahoo'"))
    op.alter_column('securities', 'asset_class',
               existing_type=sa.Enum('equity_kr', 'equity_us', 'commodity', 'currency_pair', name='assetclass', native_enum=False),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.alter_column('recurring_schedules', 'type',
               existing_type=sa.Enum('income', 'expense', 'transfer', name='scheduletype', native_enum=False),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.alter_column('rebalancing_alerts', 'threshold',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('portfolio_targets', 'target_ratio',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('goal_assets', 'target_amount',
               existing_type=sa.Numeric(precision=18, scale=0),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('entry_groups', 'group_type',
               existing_type=sa.Enum('transfer', 'trade', 'adjustment', name='grouptype', native_enum=False),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.alter_column('entries', 'type',
               existing_type=sa.Enum('income', 'expense', 'transfer_in', 'transfer_out', 'buy', 'sell', 'dividend', 'interest', 'fee', 'adjustment', name='entrytype', native_enum=False),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.alter_column('categories', 'direction',
               existing_type=sa.Enum('income', 'expense', name='categorydirection', native_enum=False),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.alter_column('api_keys', 'service',
               existing_type=sa.Enum('tavily', 'serpapi', 'openai', 'anthropic', 'google', 'mistral', 'custom_llm', name='api_service_type_enum', native_enum=False),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
    op.alter_column('ai_insights', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('accounts', 'interest_type',
               existing_type=sa.Enum('simple', 'compound', name='interesttype', native_enum=False),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.alter_column('accounts', 'account_type',
               existing_type=sa.Enum('cash', 'deposit', 'savings', 'parking', 'investment', name='accounttype', native_enum=False),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_budget_allocations_user_id'), table_name='budget_allocations')
    op.drop_table('budget_allocations')
    op.drop_table('asset_snapshots')
    op.drop_index('ix_clusters_created', table_name='news_clusters')
    op.drop_index('ix_clusters_category', table_name='news_clusters')
    op.drop_table('news_clusters')
    op.drop_index('ix_news_external_id', table_name='news_articles')
    op.drop_index('ix_news_category_created', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_budget_periods_user_id'), table_name='budget_periods')
    op.drop_table('budget_periods')
    # ### end Alembic commands ###
