"""initial

Revision ID: f4e46aec66d7
Revises: 
Create Date: 2026-04-10 18:45:07.518731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e46aec66d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_type', sa.Enum('CASH', 'DEPOSIT', 'SAVINGS', 'PARKING', 'INVESTMENT', name='accounttype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('institution', sa.String(length=50), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('interest_type', sa.Enum('SIMPLE', 'COMPOUND', name='interesttype'), nullable=True),
    sa.Column('monthly_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('budget_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_start_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_periods_user_id'), 'budget_periods', ['user_id'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('INCOME', 'EXPENSE', name='categorydirection'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'direction', 'name', name='uq_category_user_direction_name')
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('entry_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_type', sa.Enum('TRANSFER', 'TRADE', 'ADJUSTMENT', name='grouptype'), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_groups_user_id'), 'entry_groups', ['user_id'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('asset_class', sa.Enum('EQUITY_KR', 'EQUITY_US', 'COMMODITY', 'CURRENCY_PAIR', name='assetclass'), nullable=False),
    sa.Column('data_source', sa.Enum('YAHOO', 'MANUAL', name='datasource'), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_source', name='uq_security_symbol_source')
    )
    op.create_index(op.f('ix_securities_symbol'), 'securities', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('investment_prompt', sa.Text(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('account_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('holdings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'snapshot_date', name='uq_account_snapshot_date')
    )
    op.create_index(op.f('ix_account_snapshots_account_id'), 'account_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_snapshots_user_id'), 'account_snapshots', ['user_id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('generated_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_insights_user_date', 'ai_insights', ['user_id', 'generated_date'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('service', sa.Enum('TAVILY', 'SERPAPI', 'OPENAI', 'ANTHROPIC', 'GOOGLE', 'MISTRAL', 'CUSTOM_LLM', name='apiservicetype'), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service', name='uq_api_key_user_service')
    )
    op.create_table('asset_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_krw', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_snapshot_user_date')
    )
    op.create_table('budget_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'period_start', name='uq_allocation_user_cat_period')
    )
    op.create_index(op.f('ix_budget_allocations_user_id'), 'budget_allocations', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_state', sa.JSON(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('llm_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('default_model', sa.String(length=100), nullable=False),
    sa.Column('inference_model', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('portfolio_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('target_ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_type', name='uq_portfolio_user_asset_type')
    )
    op.create_table('rebalancing_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('deviations', sa.JSON(), nullable=False),
    sa.Column('suggestion', sa.JSON(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='scheduletype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('schedule_day', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('executed_count', sa.Integer(), nullable=False),
    sa.Column('source_account_id', sa.Uuid(), nullable=True),
    sa.Column('target_account_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('security_id', sa.Uuid(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_schedules_user_id'), 'recurring_schedules', ['user_id'], unique=False)
    op.create_table('security_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'price_date', name='uq_price_security_date')
    )
    op.create_index(op.f('ix_security_prices_security_id'), 'security_prices', ['security_id'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('entry_group_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('security_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER_IN', 'TRANSFER_OUT', 'BUY', 'SELL', 'DIVIDEND', 'INTEREST', 'FEE', 'ADJUSTMENT', name='entrytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('recurring_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('transacted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_group_id'], ['entry_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recurring_schedule_id'], ['recurring_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entries_account_security', 'entries', ['account_id', 'security_id'], unique=False)
    op.create_index('ix_entries_account_transacted', 'entries', ['account_id', 'transacted_at'], unique=False)
    op.create_index('ix_entries_user_category_transacted', 'entries', ['user_id', 'category_id', 'transacted_at'], unique=False)
    op.create_index('ix_entries_user_transacted', 'entries', ['user_id', 'transacted_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_index('ix_entries_user_transacted', table_name='entries')
    op.drop_index('ix_entries_user_category_transacted', table_name='entries')
    op.drop_index('ix_entries_account_transacted', table_name='entries')
    op.drop_index('ix_entries_account_security', table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_security_prices_security_id'), table_name='security_prices')
    op.drop_table('security_prices')
    op.drop_index(op.f('ix_recurring_schedules_user_id'), table_name='recurring_schedules')
    op.drop_table('recurring_schedules')
    op.drop_table('rebalancing_alerts')
    op.drop_table('portfolio_targets')
    op.drop_table('llm_settings')
    op.drop_table('goal_assets')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_budget_allocations_user_id'), table_name='budget_allocations')
    op.drop_table('budget_allocations')
    op.drop_table('asset_snapshots')
    op.drop_table('api_keys')
    op.drop_index('ix_ai_insights_user_date', table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_account_snapshots_user_id'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_account_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_table('users')
    op.drop_index(op.f('ix_securities_symbol'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_entry_groups_user_id'), table_name='entry_groups')
    op.drop_table('entry_groups')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_budget_periods_user_id'), table_name='budget_periods')
    op.drop_table('budget_periods')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
